[tasks.test]
cmd = "pytest"

[tasks.test-multienv]
cmd = "tox"

[tasks.lint]
sequence = [
  { cmd = "ruff check $path" },
  { cmd = "mypy $path" },
]
args = [
  { name = "path", positional = true, default = "" }
]

[tasks.build-man]
script = "src.helpers.docs:build_man_page"

[tasks.build-docs]
cmd = "zensical build"

[tasks.serve-docs]
cmd = "zensical serve"
