"""Protocols that mimic some of the stdlib collection ABCs.

We only implement a few protocols for type checking of JSON. These protocols are
not used at runtime (even the runtime_checkable decorator is there only for type
checking)

It is not worthwhile for us to accurately reproduce the ABCs with all their base
classes and dependencies, but the result is close enough.

The annotations are based on [typing.pyi] from the typeshed.

[typing.pyi]: https://github.com/python/typeshed/blob/main/stdlib/typing.pyi
"""
# ruff: noqa: D102, D105, PLW1641

from collections.abc import Collection, ItemsView, Iterable, Iterator, KeysView, Reversible, ValuesView
from typing import Protocol, overload, runtime_checkable


@runtime_checkable
class SequenceProtocol[InT, OutT](Reversible[OutT], Collection[OutT], Protocol):
    """Protocol that mimics the [`Sequence`][collections.abc.Sequence] ABC.

    Type Parameters:
        InT: The (covariant) parameter type of the sequence.
        OutT: The (contravariant) result type of the sequence.
    """

    # Abstract methods
    @overload
    def __getitem__(self, index: int, /) -> OutT: ...
    @overload
    def __getitem__(self, index: 'slice[int | None]', /) -> 'SequenceProtocol[InT, OutT]': ...

    # Mixin methods
    def index(self, value: InT, start: int = 0, stop: int = ..., /) -> int: ...
    def count(self, value: InT, /) -> int: ...
    def __contains__(self, value: object, /) -> bool: ...
    def __iter__(self) -> Iterator[OutT]: ...
    def __reversed__(self) -> Iterator[OutT]: ...


@runtime_checkable
class MutableSequenceProtocol[InT, OutT](SequenceProtocol[InT, OutT], Protocol):
    """Protocol that mimics the [`MutableSequence`][collections.abc.MutableSequence] ABC.

    Type Parameters:
        InT: The (covariant) parameter type of the sequence.
        OutT: The (contravariant) result type of the sequence.
    """

    # Abstract methods
    def insert(self, index: int, value: InT, /) -> None: ...
    @overload
    def __getitem__(self, index: int, /) -> OutT: ...
    @overload
    def __getitem__(self, index: 'slice[int | None]', /) -> 'MutableSequenceProtocol[InT, OutT]': ...
    @overload
    def __setitem__(self, index: int, value: InT, /) -> None: ...
    @overload
    def __setitem__(self, index: 'slice[int | None]', value: Iterable[OutT], /) -> None: ...
    @overload
    def __delitem__(self, index: int, /) -> None: ...
    @overload
    def __delitem__(self, index: 'slice[int | None]', /) -> None: ...

    # Mixin methods
    def append(self, value: InT, /) -> None: ...
    def clear(self) -> None: ...
    def extend(self, values: Iterable[InT], /) -> None: ...
    def reverse(self) -> None: ...
    def pop(self, index: int = -1, /) -> OutT: ...
    def remove(self, value: InT, /) -> None: ...
    def __iadd__(self, values: Iterable[InT], /) -> Iterable[OutT]: ...


@runtime_checkable
class MappingProtocol[K, V](Collection[K], Protocol):
    """Protocol that mimics the [`Mapping`][collections.abc.Mapping] ABC.

    Type Parameters:
        K: The type of keys.
        V: The type of values.
    """

    # Abstract methods
    def __getitem__(self, key: K, /) -> V: ...

    # Mixin methods
    @overload
    def get(self, key: K, /) -> V | None: ...
    @overload
    def get(self, key: K, default: V, /) -> V: ...
    def items(self) -> ItemsView[K, V]: ...
    def keys(self) -> KeysView[K]: ...
    def values(self) -> ValuesView[V]: ...
    def __contains__(self, key: object, /) -> bool: ...
    def __eq__(self, other: object, /) -> bool: ...


@runtime_checkable
class MutableMappingProtocol[K, V](MappingProtocol[K, V], Protocol):
    """Protocol that mimics the [`MutableMapping`][collections.abc.MutableMapping] ABC.

    Type Parameters:
        K: The type of keys.
        V: The type of values.
    """

    # Abstract methods
    def __setitem__(self, key: K, value: V, /) -> None: ...
    def __delitem__(self, key: K, /) -> None: ...

    # Mixin methods
    def clear(self) -> None: ...
    @overload
    def pop(self, key: K, /) -> V: ...
    @overload
    def pop(self, key: K, default: V, /) -> V: ...
    def popitem(self) -> tuple[K, V]: ...
    @overload
    def setdefault(self: 'MutableMappingProtocol[K, V | None]', key: K, default: None = None, /) -> V | None: ...
    @overload
    def setdefault(self, key: K, default: V, /) -> V: ...
    @overload
    def update(self, m: MappingProtocol[K, V], /) -> None: ...
    @overload
    def update(self: MappingProtocol[str, V], m: MappingProtocol[str, V], /, **kwargs: V) -> None: ...
    @overload
    def update(self, m: Iterable[tuple[K, V]], /) -> None: ...
    @overload
    def update(self: MappingProtocol[str, V], m: Iterable[tuple[str, V]], /, **kwargs: V) -> None: ...
    @overload
    def update(self: MappingProtocol[str, V], /, **kwargs: V) -> None: ...
