#!/usr/bin/env fish
#
# This file and `link-dotfiles-worker` are dotfile management scripts. Usage is discussed in
#   https://github.com/v--/viat/blob/master/examples/dotfiles

which gum >/dev/null
or exit 1

# We rely on the worker being in the same directory because, while bootstrapping the dotfiles,
# $PATH may not yet contain the directory with these scripts.
set worker (status dirname)/link-dotfiles-worker

if test ! -e "$worker"
    gum log --level fatal "Could not find the auxiliary script `link-dotfiles-worker`` in the same directory as `link-dotfiles`."
    exit 1
end

if test -z "$XDG_CONFIG_HOME"
    set --global --export XDG_CONFIG_HOME $HOME/.config
end

if test -z "$XDG_DATA_HOME"
    set --global --export XDG_DATA_HOME $HOME/.local/share
end

for line in (viat shell-export)
    eval "export $line"
    set dest (eval echo $dest)

    if echo $scopes | grep --quiet $hostname
        if test -n "$privileged"
            sudo $worker $path $dest $strategy
        else
            $worker $path $dest $strategy
        end
    end
end
